# Generated by Django 4.2 on 2023-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fathername', models.CharField(max_length=500)),
                ('contactnum', models.IntegerField()),
                ('classname', models.CharField(max_length=500)),
            ],
        ),
    ]
